services:
  rstudio:
    image: rocker/tidyverse
    ports:
      - "8787:8787"
    environment:
      PASSWORD: rstudio
    volumes:
      - ./.rstudio_config:/home/rstudio/.config/rstudio
      - .:/home/rstudio